### PR TITLE
Statistics

### PR DESCRIPTION
**Pull request by heinosasshallik**
The statistics are generated based on the category the user chooses in the `QuestionFilterCategory` component

### CODE REVIEW

**Comment by priitkaard** [comment]
Seems very nice, only one comment about style namings :)

**Comment by heinosasshallik** [comment]
@priitkaard where did you leave the comment? Or what should I fix?

**Comment by priitkaard** [comment]
QuestionStatistics.vue

**Comment by heinosasshallik** [comment]
What do you want me to change about it? I don't see any comments

**Comment by priitkaard** [comment]
Can’t find on mobile how to approve, but approved :D

**Pull request merged**
